name = "HyperdimensionalComputing"
uuid = "ebb7690e-f605-4e7a-86a0-727dbed6b293"
authors = ["Carlos Vigil-Vásquez", "Dimi Boeckaerts", "Michiel Stock", "Steff Taelman"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[extensions]
UnicodePlotting = "UnicodePlots"

[compat]
Distributions = "0.25.120"
LinearAlgebra = "1.11.0"
Random = "1.11.0"
StatsBase = "0.34.6"
UnicodePlots = "3.8.1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
